server:
  port: 8090
  servlet:
    context-path: /api


spring:

  application:
    name: budgetbee

  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    show-sql: true
    open-in-view: false

  main:
    banner-mode: off

  # MAIL

  mail:
    host: smtp.gmail.com
    port: 587
    # username -> equivale alla email senza @gmail.com
    username: ${MAIL_USERNAME}
    # password -> passaword fornita da google per l'utilizzo di applicaizoni di terze parti
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true

spring-doc:
  swagger-ui:
    enabled: true
    # localhost:8090/api/swagger-ui.html
    path: /swagger-ui.html

logging:
  level:
    com.sav.budgetbee: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info


# CUSTOM PROPERTIES

application:
  mail:
    # EMAIL PER ESTESO
    sender: ${MAIL}
  security:
    jwt:
      tokenType: Bearer
      secret-key: ${KEY_SECRET}
      expiration: 86400000 # millisecondi -> 1 giorno
